### PR TITLE
Keep Hetzner's snake_case for properties

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Don't you think it would be easier to just keep the properties as they're coming, to be compatible with https://docs.hetzner.cloud/#servers-get-a-server ?

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Hey @ThomasLandauer,

yep this is easier but would be a breaking change which I wouldn't like to do.

**Comment by LKaemmerling** [comment]
> I just wanted to hear what you say in general ;-)
> My plan about the BC break would be to _add_ the snake case properties (like I did it now). And `@deprecate` the others. And then, in some future version (3?), remove them.

Hey @ThomasLandauer,

yep this is fine for me :)

**Comment by ThomasLandauer** [comment]
Done :-)

**Review by LKaemmerling — APPROVED** [review]
Thank you! Good Job

**Pull request merged**
