### PR TITLE
Implemented metrics function on Server Model

### PR DESCRIPTION
**Pull request by paulus7**
Hey, I completed your function for getting the metrics of a server. Is that okay or would it be better to create a model for metrics?

### CODE REVIEW

**Comment by LKaemmerling** [comment]
LGTM, but can you please add a test for the Method :)?

**Comment by LKaemmerling** [comment]
FYI: You can test against the exact response values from https://docs.hetzner.cloud/#servers-get-metrics-for-a-server

**Comment by paulus7** [comment]
my bad, changed it :)

**Comment by LKaemmerling** [comment]
Thank you!

**Comment by LKaemmerling** [comment]
FYI: Was released with https://github.com/LKDevelopment/hetzner-cloud-php-sdk/releases/tag/v1.4.0

**Pull request merged**
